### ISSUE TITLE
error in 1.16.5 when open the anvil

### ISSUE THREAD

**Issue by josekatriel** [M0diis/M0-AntiAnvilRename#1]
[02:00:39] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to M0-AntiAnvilRename v1.11
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1414) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.ContainerAnvil.e(ContainerAnvil.java:279) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.ContainerAnvil.a(ContainerAnvil.java:300) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:830) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.PacketPlayInItemName.a(SourceFile:30) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.PacketPlayInItemName.a(SourceFile:8) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1037) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack org.bukkit.inventory.AnvilInventory.getFirstItem()'
	at me.M0dii.AntiAnvilRename.AnvilListener.cancelRename(AnvilListener.java:62) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor357.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.16.5.jar:3094-Spigot-9fb885e-fae895a]
	... 21 more

**Comment by M0diis** [comment]
What server jar are you using?
